{% set name = "mypy_extensions" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mypy_extensions-{{ version }}.tar.gz
  sha256: 75dbf8955dc00442a438fc4d0666508a9a97b6bd41aa2f0ffe9d2f2725af0782

build:
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - mypy_extensions
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.mypy-lang.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extensions for mypy
  description: |
      The 'mypy_extensions' module defines experimental extensions to the
      standard 'typing' module that are supported by the mypy typechecker.
  doc_url: https://mypy.readthedocs.io
  dev_url: https://github.com/python/mypy_extensions

extra:
  recipe-maintainers:
    - nehaljwani
    - skupr-anaconda