{% set name = "mypy_extensions" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mypy_extensions-{{ version }}.tar.gz
  sha256: 52e68efc3284861e772bbcd66823fde5ae21fd2fdb51c62a211403730b916558

build:
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - flit-core >=3.11,<4
  run:
    - python

test:
  imports:
    - mypy_extensions
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.mypy-lang.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extensions for mypy
  description: |
      The 'mypy_extensions' module defines experimental extensions to the
      standard 'typing' module that are supported by the mypy typechecker.
  doc_url: https://mypy.readthedocs.io
  dev_url: https://github.com/python/mypy_extensions

extra:
  recipe-maintainers:
    - nehaljwani
    - skupr-anaconda