# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "b9rjk0BwlJUMMUAUoBC8n8gi8kVbCC6lFzVzjPZeJ2zR4NP2PS0qn2tHBQEQWvbkH/9urQM/O/5F1WqeG0HxENKGOLOEgVVFcDf6e/ef71zPa3xn3wwINovgWaYL5xXG6Iq9ai4d8+LDL6ElhX5IKwHY8IuMoX3S8xHJ8hQGGe+sv8DdRKBqEfPArPieq6vvyvRI+fCyjXdhNinEJ5LsIHPbAXYtHTPXMNNb/jzmTT5ir078cCcqiuzSCk6ywb2QPrUesTMzPCL7u1vZxfXo2KQJEh3/2GePEl0VHb3zQnuRK4HwexZ+mAvIi+kYxs4dYscLzh6f4RMTYBzCdRx2cD+a7cwL4XoAZCMK8yCAXYwB3Po5Vbkgq9RbaIcPjgSx+gM7OSKvmAfWkNII11S135EiZe/U1wgDzM/jtiLNraS4mUcOoCSKUHAHWcGpwR6p+rOAwc+GJYVkXLG5j0zOfhrgrShgANCv6cTE6u9uWY8MQKnIMVnUz6xP/JYnbVN0SlXjtbLpVbtfrVePnJqlF6fMfmPD4G5lab3rn859sGgS/H29Sr+4DZcRMY7FAayKwMmXNmVWIRxpAI3S0SAVBhT4a5Gf8FP00ZDkzoXKG2UirpJ355aFdIfP8OQwQUTPMeKogNzPeqWT72OUOhim32jkBnWMWDm4HJ+VwGKeSqw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
