travis:
  secure:
    BINSTAR_TOKEN: b9rjk0BwlJUMMUAUoBC8n8gi8kVbCC6lFzVzjPZeJ2zR4NP2PS0qn2tHBQEQWvbkH/9urQM/O/5F1WqeG0HxENKGOLOEgVVFcDf6e/ef71zPa3xn3wwINovgWaYL5xXG6Iq9ai4d8+LDL6ElhX5IKwHY8IuMoX3S8xHJ8hQGGe+sv8DdRKBqEfPArPieq6vvyvRI+fCyjXdhNinEJ5LsIHPbAXYtHTPXMNNb/jzmTT5ir078cCcqiuzSCk6ywb2QPrUesTMzPCL7u1vZxfXo2KQJEh3/2GePEl0VHb3zQnuRK4HwexZ+mAvIi+kYxs4dYscLzh6f4RMTYBzCdRx2cD+a7cwL4XoAZCMK8yCAXYwB3Po5Vbkgq9RbaIcPjgSx+gM7OSKvmAfWkNII11S135EiZe/U1wgDzM/jtiLNraS4mUcOoCSKUHAHWcGpwR6p+rOAwc+GJYVkXLG5j0zOfhrgrShgANCv6cTE6u9uWY8MQKnIMVnUz6xP/JYnbVN0SlXjtbLpVbtfrVePnJqlF6fMfmPD4G5lab3rn859sGgS/H29Sr+4DZcRMY7FAayKwMmXNmVWIRxpAI3S0SAVBhT4a5Gf8FP00ZDkzoXKG2UirpJ355aFdIfP8OQwQUTPMeKogNzPeqWT72OUOhim32jkBnWMWDm4HJ+VwGKeSqw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
